Fix PermissionError: [Errno 13] Permission denied
Fix the issue of unclosed files in Windows system causing unauthorized access to read yaml files.

 return yaml.safe_load(file_obj.read_text('utf-8', 'ignore'))
  File "C:\Python3\lib\pathlib.py", line 1266, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Python3\lib\pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Python3\lib\pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\test\\AppData\\Local\\Temp\\tmpclbvrcwq'